sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    
    #安装任务一需要使用的工具imagemagick
    - sudo apt-get install imagemagick 
    - sudo apt install ghostscript
    
    
    #下载任务2-2需要使用的文件
    - wget "https://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
    - sudo apt install p7zip-full
    - 7z x web_log.tsv.7z

script:
  - bash test.sh
  #任务一:用bash编写一个图片批处理脚本
  #帮助文档
  - bash shell/image.sh -h  
  #对jpeg格式图片进行图片质量压缩
  - bash shell/image.sh -q 50% ./img
  #对jpeg/png/svg格式图片在保持原始宽高比的前提下压缩分辨率
  - bash shell/image.sh -p 50% ./img
  #批量添加自定义文本水印
  - bash shell/image.sh -w hello ./img
  #批量重命名
  ##前缀
  - bash shell/image.sh -r head h ./img
  ##后缀
  - bash shell/image.sh -r tail h ./img
  #将png/svg图片统一转换为jpg格式图片
  - bash shell/image.sh -t ./img
  
  #任务二：用bash编写一个文本批处理脚本，对以下附件分别进行批量处理完成相应的数据统计任务
  - bash shell/world.sh
  
  #任务三：用bash编写一个文本批处理脚本，对以下附件分别进行批量处理完成相应的数据统计任务
  #查看帮助信息
  - bash shell/web.sh -h
  #统计访问来源主机TOP100和分别对应出现的总次数
  - bash shell/web.sh -a
  #统计访问来源主机TOP 100 IP和分别对应出现的总次数
  - bash shell/web.sh -b
  #统计最频繁被访问的URL TOP 100
  - bash shell/web.sh -c
  #统计不同响应状态码的出现次数和对应百分比
  - bash shell/web.sh -d
  #分别统计不同4XX状态码对应的TOP 10 URL和对应出现的总次数
  - bash shell/web.sh -e
  #给定URL输出TOP 100访问来源主机
  - bash shell/web.sh -u /pub/winvn/readme.txt
  
  
after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
